# Generated by Django 4.2.7 on 2023-11-10 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='Accounts',
        ),
    ]
