# Generated by Django 4.2.7 on 2023-11-10 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0002_rename_userprofile_accounts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Accounts',
            new_name='Users',
        ),
    ]
