# Generated by Django 4.2.7 on 2023-11-13 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0003_rename_accounts_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='id',
        ),
        migrations.AlterField(
            model_name='users',
            name='userid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
