# Generated by Django 4.2.7 on 2023-11-15 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0007_users_phone'),
    ]

    operations = [
    ]
