# Generated by Django 4.2.7 on 2023-11-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0008_auto_20231115_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_logged_in',
            field=models.BooleanField(default=False),
        ),
    ]
