# Generated by Django 4.2.7 on 2023-11-18 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TasksApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='status',
            field=models.CharField(default='active', max_length=255),
        ),
    ]
