# Generated by Django 4.2.7 on 2023-11-16 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileApp', '0001_initial'),
    ]

    operations = [
    ]
