# Generated by Django 4.2.7 on 2023-11-16 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileApp', '0002_auto_20231117_0025'),
    ]

    operations = [
    ]
