# Generated by Django 4.2.7 on 2023-11-16 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileApp', '0004_auto_20231117_0030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='title',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='user',
        ),
    ]
