# Generated by Django 4.2.7 on 2023-11-16 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileApp', '0005_remove_tasks_deadline_remove_tasks_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tasks',
        ),
    ]
